# Generated by Django 3.1.6 on 2021-02-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=150)),
                ('image', models.ImageField(default='null', upload_to='')),
                ('cases', models.DateTimeField(auto_now_add=True)),
                ('death', models.CharField(max_length=50)),
                ('lethality', models.CharField(max_length=50)),
            ],
        ),
    ]
