# Generated by Django 3.1.6 on 2021-02-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=150, verbose_name='Name')),
                ('job', models.CharField(max_length=150, verbose_name='Cases')),
                ('image', models.ImageField(default='null', upload_to='regiones', verbose_name='Miniatura')),
                ('state', models.BooleanField(verbose_name='¿Estado?')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Name')),
                ('cases', models.CharField(max_length=150, verbose_name='Cases')),
                ('deaths', models.CharField(max_length=150, verbose_name='Deaths')),
                ('lethality', models.CharField(max_length=150, verbose_name='Lethality')),
                ('image', models.ImageField(default='null', upload_to='regiones', verbose_name='Miniatura')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
            ],
        ),
    ]
