# Generated by Django 3.1.6 on 2021-02-17 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Articulo',
            new_name='Region',
        ),
    ]
