# Generated by Django 3.1.6 on 2021-02-17 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='names',
            new_name='name',
        ),
    ]
