# Generated by Django 3.1.6 on 2021-02-17 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0002_auto_20210217_1032'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='death',
            new_name='deaths',
        ),
    ]
